/*
 * This source file was generated by the Gradle 'init' task
 */
package pa1_v2;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// import pa1_v2.BankAccountTest;

// import banktest file 

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }
}
